language: python
# if command bellow need to executed in sudo
# add this line.
# sudo: required
python:
  - 3.7
install:
  - pip install poetry
  - poetry install
script:
  - pytest --cov=project --cov-fail-under=50 --cov-report=term-missing tests