name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: pyproject:$(date +%s)

    - name: Prepare repo
      uses: actions/checkout@v2

    - name: Test
      uses: onichandame/python-test-action@master